# Generated by Django 4.2 on 2023-04-23 14:07

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guest', max_length=100)),
                ('patient_id', models.CharField(default=app.models.incre_patient_id, editable=False, max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('bp', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('fbs', models.IntegerField()),
                ('restecg', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0)),
                ('thalach', models.IntegerField()),
                ('exang', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('oldpeak', models.FloatField()),
                ('slope', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0)),
                ('ca', models.IntegerField()),
                ('thal', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
