# Generated by Django 4.2 on 2023-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='first_name', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='last_name', max_length=30),
        ),
    ]
