# Generated by Django 4.2 on 2023-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_patient_name_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='fbs',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
